name: ingest-accounts-into-s3-pipeline

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  ingest-accounts-into-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          make install

      - name: Ingest accounts into S3
        env:
          AWS_ID: ${{ secrets.AWS_ID }}
          AWS_KEY: ${{ secrets.AWS_KEY }}
        run: python pipelines/ingestion_pipeline.py
