name: ingest-accounts-into-s3-pipeline

on:
  workflow_dispatch:

jobs:
  ingest-accounts-into-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install

      - name: Ingest accounts into S3
        run: python scripts/ingest_accounts_into_s3.py